blank_issues_enabled: false
contact_links:
  - name: Suggest ideas
    url: https://github.com/jiacai2050/my-works/discussions/categories/ideas
    about: Share ideas for new features.
  - name: Ask questions
    url: https://github.com/jiacai2050/my-works/discussions/categories/q-a
    about: Ask the community for help.
