name: VC CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'video-compress/**'
  push:
    branches:
      - main
    paths:
      - 'video-compress/**'

defaults:
  run:
    working-directory: video-compress

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install
        run: |
          pip install hatch
          pip install ruff
      - name: lint
        run: |
          make lint
