name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'zms/**'
      - '.github/workflows/zms-ci.yml'
  push:
    branches:
      - main
    paths:
      - 'zms/**'
      - '.github/workflows/zms-ci.yml'

defaults:
  run:
    working-directory: zms

jobs:
  test:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: mlugg/setup-zig@v2
      - name: fmt and test(windows)
        if: matrix.os == 'windows-latest'
        run: |
          zig.exe fmt --check .
          zig.exe build
          zig.exe build test
      - name: fmt and test(unix)
        if: matrix.os != 'windows-latest'
        run: |
          zig fmt --check .
          zig build
          zig build test
